name: 'ANDS Validation'
description: 'Validates ands.json declarations for schema compliance and cryptographic integrity.'
inputs:
  path:
    description: 'Path to the ands.json file'
    required: true
    default: '.well-known/ands.json'
  baseline-path:
    description: 'Path to baseline ands.json for delta comparison'
    required: false
  live-scan:
    description: 'Whether to perform live scan verification'
    required: false
    default: 'false'
  generate-html:
    description: 'Whether to generate an HTML report artifact'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/tools/requirements.txt
        pip install .
      shell: bash
    - name: Run ANDS CI Dashboard
      run: |
        ARGS="${{ inputs.path }}"
        if [ -n "${{ inputs.baseline-path }}" ]; then
          ARGS="$ARGS --baseline ${{ inputs.baseline-path }}"
        fi
        if [ "${{ inputs.live-scan }}" = "true" ]; then
          ARGS="$ARGS --live"
        fi
        if [ "${{ inputs.generate-html }}" = "true" ]; then
          mkdir -p ands-reports
          ARGS="$ARGS --html ands-reports/dashboard.html"
        fi
        PYTHONPATH=${{ github.action_path }} python3 ${{ github.action_path }}/tools/ands_ci.py $ARGS
      shell: bash
    - name: Upload HTML Report
      if: inputs.generate-html == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ands-compliance-report
        path: ands-reports/dashboard.html
branding:
  icon: 'shield'
  color: 'blue'
